---
title: "About Me"
description: Description about the website 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Scout is a graduate student in the Masters of Environmental Data Science Program at the Bren School of Environmental Science and Management at the University of California, Santa Barbara. In 2018, she received her Bachelor's Degree from Harvard University, where she studied Integrative Biology and Energy & the Environment. At Harvard, Scout was interested in ecology and evolution and she conducted plant phylogenetics research. She also led consulting projects for nonprofit groups with the Harvard College Conservation Society. On a summer internship, a unique interdisciplinary conservation project (using beehives to reduce human-elephant conflict and protect agriculture) shifted her interest from ecology to human-environmental systems and conservation conflict resolution. Scout believes in studying the environment in the complex way that it exists in relationship with human populations. As such, she has spent the last 3 years working in Oakland, California with nonprofit groups such as No Kid Hungry and FoodCorps to expand access to healthy school meals for students in urban school districts. Scout believes that every person has the right to nutritious, culturally-appropriate food. She oversaw food system programs by managing data about procurement, participation, and waste; Scout hopes her growing skills as a data scientist can help her to transform food systems to be more sustainable and equitable.



